/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.przelicznik_jednostek;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.lang.model.util.Elements;

/**
 *
 * @author musialantoni
 */
public class Przelicznik_jednostek extends javax.swing.JFrame {

    /**
     * Creates new form Przelicznik_jednostek
     */
    public Przelicznik_jednostek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDHistoria = new javax.swing.JDialog();
        jOPHistoria = new javax.swing.JOptionPane();
        jDPomoc = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDOprogramie = new javax.swing.JDialog();
        jOPOprogramie = new javax.swing.JOptionPane();
        jPTresc = new javax.swing.JPanel();
        jTBTresc = new javax.swing.JTabbedPane();
        jPStrona1 = new javax.swing.JPanel();
        jLTytulTemperatura = new javax.swing.JLabel();
        jTFKelwiny_Temperatura = new javax.swing.JTextField();
        jTFCelcjusze_Temperatura = new javax.swing.JTextField();
        jBPrzelicz_Temperatura = new javax.swing.JButton();
        jBReset_Temperatura = new javax.swing.JButton();
        jBPomoc_Temperatura = new javax.swing.JButton();
        jLPomoc1_Temperatura = new javax.swing.JLabel();
        jLPomoc2_Temperatura = new javax.swing.JLabel();
        jLPomoc3_Temperatura = new javax.swing.JLabel();
        jLPomoc4_Temperatura = new javax.swing.JLabel();
        jLZapisano1 = new javax.swing.JLabel();
        jPStrona2 = new javax.swing.JPanel();
        jLTytulOdleglosc = new javax.swing.JLabel();
        jTFCentymetry_Odleglosc = new javax.swing.JTextField();
        jTFMetry_Odleglosc = new javax.swing.JTextField();
        jBReset_Odleglosc = new javax.swing.JButton();
        jBPrzelicz_Odleglosc = new javax.swing.JButton();
        jBPomoc_Odleglosc = new javax.swing.JButton();
        jLPomoc1_Odleglosc = new javax.swing.JLabel();
        jLPomoc2_Odleglosc = new javax.swing.JLabel();
        jLPomoc3_Odleglosc = new javax.swing.JLabel();
        jLPomoc4_Odleglosc = new javax.swing.JLabel();
        jLZapisano2 = new javax.swing.JLabel();
        jMBMenu = new javax.swing.JMenuBar();
        jMPlik = new javax.swing.JMenu();
        jMIPokazHistorie = new javax.swing.JMenuItem();
        jMIZamknij = new javax.swing.JMenuItem();
        jMOProgramie = new javax.swing.JMenu();

        jDHistoria.setBackground(java.awt.Color.darkGray);
        jDHistoria.setBounds(new java.awt.Rectangle(244, 244, 244, 244));
        jDHistoria.setIconImages(null);
        jDHistoria.setName("Historia"); // NOI18N
        jDHistoria.setUndecorated(true);

        jOPHistoria.setBackground(java.awt.Color.darkGray);
        jOPHistoria.setForeground(java.awt.Color.white);
        jOPHistoria.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jOPHistoriaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jDHistoriaLayout = new javax.swing.GroupLayout(jDHistoria.getContentPane());
        jDHistoria.getContentPane().setLayout(jDHistoriaLayout);
        jDHistoriaLayout.setHorizontalGroup(
            jDHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOPHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDHistoriaLayout.setVerticalGroup(
            jDHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOPHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jOptionPane1.setBackground(java.awt.Color.darkGray);
        jOptionPane1.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout jDPomocLayout = new javax.swing.GroupLayout(jDPomoc.getContentPane());
        jDPomoc.getContentPane().setLayout(jDPomocLayout);
        jDPomocLayout.setHorizontalGroup(
            jDPomocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDPomocLayout.setVerticalGroup(
            jDPomocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jOPOprogramie.setBackground(java.awt.Color.darkGray);
        jOPOprogramie.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout jDOprogramieLayout = new javax.swing.GroupLayout(jDOprogramie.getContentPane());
        jDOprogramie.getContentPane().setLayout(jDOprogramieLayout);
        jDOprogramieLayout.setHorizontalGroup(
            jDOprogramieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOPOprogramie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDOprogramieLayout.setVerticalGroup(
            jDOprogramieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOPOprogramie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Przelicznik jednostek");
        setBackground(java.awt.Color.darkGray);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 400));

        jPTresc.setBackground(java.awt.Color.pink);
        jPTresc.setForeground(java.awt.Color.white);

        jTBTresc.setBackground(java.awt.Color.yellow);
        jTBTresc.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jPStrona1.setBackground(java.awt.Color.pink);
        jPStrona1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLTytulTemperatura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTytulTemperatura.setForeground(java.awt.Color.white);
        jLTytulTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTytulTemperatura.setText("Przelicznik Kelwinów na Celcjusze");
        jLTytulTemperatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTFKelwiny_Temperatura.setBackground(java.awt.Color.pink);
        jTFKelwiny_Temperatura.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTFKelwiny_Temperatura.setForeground(java.awt.Color.white);
        jTFKelwiny_Temperatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFKelwiny_Temperatura.setText("Kelwiny");
        jTFKelwiny_Temperatura.setMaximumSize(new java.awt.Dimension(170, 25));
        jTFKelwiny_Temperatura.setPreferredSize(new java.awt.Dimension(170, 25));

        jTFCelcjusze_Temperatura.setBackground(java.awt.Color.pink);
        jTFCelcjusze_Temperatura.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTFCelcjusze_Temperatura.setForeground(java.awt.Color.white);
        jTFCelcjusze_Temperatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFCelcjusze_Temperatura.setText("Celcjusze");

        jBPrzelicz_Temperatura.setBackground(java.awt.Color.pink);
        jBPrzelicz_Temperatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBPrzelicz_Temperatura.setForeground(java.awt.Color.white);
        jBPrzelicz_Temperatura.setText("Przelicz");
        jBPrzelicz_Temperatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPrzelicz_Temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrzelicz_TemperaturaActionPerformed(evt);
            }
        });

        jBReset_Temperatura.setBackground(java.awt.Color.pink);
        jBReset_Temperatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBReset_Temperatura.setForeground(java.awt.Color.white);
        jBReset_Temperatura.setText("Reset");
        jBReset_Temperatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBReset_Temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReset_TemperaturaActionPerformed(evt);
            }
        });

        jBPomoc_Temperatura.setBackground(java.awt.Color.pink);
        jBPomoc_Temperatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBPomoc_Temperatura.setForeground(java.awt.Color.white);
        jBPomoc_Temperatura.setText("Pomoc");
        jBPomoc_Temperatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPomoc_Temperatura.setMaximumSize(new java.awt.Dimension(80, 30));
        jBPomoc_Temperatura.setPreferredSize(new java.awt.Dimension(80, 30));
        jBPomoc_Temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPomoc_TemperaturaActionPerformed(evt);
            }
        });
        jBPomoc_Temperatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBPomoc_TemperaturaKeyPressed(evt);
            }
        });

        jLPomoc1_Temperatura.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc1_Temperatura.setForeground(java.awt.Color.white);
        jLPomoc1_Temperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPomoc1_Temperatura.setMaximumSize(new java.awt.Dimension(357, 16));
        jLPomoc1_Temperatura.setPreferredSize(new java.awt.Dimension(357, 16));

        jLPomoc2_Temperatura.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc2_Temperatura.setForeground(java.awt.Color.white);
        jLPomoc2_Temperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPomoc2_Temperatura.setMaximumSize(new java.awt.Dimension(357, 16));
        jLPomoc2_Temperatura.setPreferredSize(new java.awt.Dimension(357, 16));

        jLPomoc3_Temperatura.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc3_Temperatura.setForeground(java.awt.Color.white);
        jLPomoc3_Temperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPomoc3_Temperatura.setMaximumSize(new java.awt.Dimension(357, 16));
        jLPomoc3_Temperatura.setPreferredSize(new java.awt.Dimension(357, 16));

        jLPomoc4_Temperatura.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc4_Temperatura.setForeground(java.awt.Color.white);
        jLPomoc4_Temperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLZapisano1.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLZapisano1.setForeground(java.awt.Color.green);
        jLZapisano1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLZapisano1.setPreferredSize(new java.awt.Dimension(44, 15));

        javax.swing.GroupLayout jPStrona1Layout = new javax.swing.GroupLayout(jPStrona1);
        jPStrona1.setLayout(jPStrona1Layout);
        jPStrona1Layout.setHorizontalGroup(
            jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStrona1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCelcjusze_Temperatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStrona1Layout.createSequentialGroup()
                        .addComponent(jBReset_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBPrzelicz_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLZapisano1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPStrona1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTytulTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPStrona1Layout.createSequentialGroup()
                        .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLPomoc4_Temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBPomoc_Temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLPomoc2_Temperatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLPomoc1_Temperatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLPomoc3_Temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStrona1Layout.createSequentialGroup()
                    .addContainerGap(170, Short.MAX_VALUE)
                    .addComponent(jTFKelwiny_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(139, 139, 139)))
        );
        jPStrona1Layout.setVerticalGroup(
            jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStrona1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTytulTemperatura)
                .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPStrona1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jTFCelcjusze_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPStrona1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBPrzelicz_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBReset_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jLPomoc1_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLPomoc2_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLPomoc3_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStrona1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLZapisano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))))
                    .addGroup(jPStrona1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLPomoc4_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPomoc_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPStrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPStrona1Layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(jTFKelwiny_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        jTBTresc.addTab("Temperatura", jPStrona1);

        jPStrona2.setBackground(java.awt.Color.pink);
        jPStrona2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLTytulOdleglosc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTytulOdleglosc.setForeground(java.awt.Color.white);
        jLTytulOdleglosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTytulOdleglosc.setText("Przelicznik centymetrów na metry");
        jLTytulOdleglosc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTFCentymetry_Odleglosc.setBackground(java.awt.Color.pink);
        jTFCentymetry_Odleglosc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTFCentymetry_Odleglosc.setForeground(java.awt.Color.white);
        jTFCentymetry_Odleglosc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFCentymetry_Odleglosc.setText("Centymetry");
        jTFCentymetry_Odleglosc.setMaximumSize(new java.awt.Dimension(170, 30));
        jTFCentymetry_Odleglosc.setPreferredSize(new java.awt.Dimension(170, 30));

        jTFMetry_Odleglosc.setBackground(java.awt.Color.pink);
        jTFMetry_Odleglosc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTFMetry_Odleglosc.setForeground(java.awt.Color.white);
        jTFMetry_Odleglosc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFMetry_Odleglosc.setText("Metry");
        jTFMetry_Odleglosc.setMaximumSize(new java.awt.Dimension(170, 30));
        jTFMetry_Odleglosc.setPreferredSize(new java.awt.Dimension(170, 30));

        jBReset_Odleglosc.setBackground(java.awt.Color.pink);
        jBReset_Odleglosc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBReset_Odleglosc.setForeground(java.awt.Color.white);
        jBReset_Odleglosc.setText("Reset");
        jBReset_Odleglosc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBReset_Odleglosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReset_OdlegloscActionPerformed(evt);
            }
        });

        jBPrzelicz_Odleglosc.setBackground(java.awt.Color.pink);
        jBPrzelicz_Odleglosc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBPrzelicz_Odleglosc.setForeground(java.awt.Color.white);
        jBPrzelicz_Odleglosc.setText("Przelicz");
        jBPrzelicz_Odleglosc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPrzelicz_Odleglosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrzelicz_OdlegloscActionPerformed(evt);
            }
        });

        jBPomoc_Odleglosc.setBackground(java.awt.Color.pink);
        jBPomoc_Odleglosc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBPomoc_Odleglosc.setForeground(java.awt.Color.white);
        jBPomoc_Odleglosc.setText("Pomoc");
        jBPomoc_Odleglosc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPomoc_Odleglosc.setMaximumSize(new java.awt.Dimension(80, 30));
        jBPomoc_Odleglosc.setPreferredSize(new java.awt.Dimension(80, 30));
        jBPomoc_Odleglosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPomoc_OdlegloscActionPerformed(evt);
            }
        });
        jBPomoc_Odleglosc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBPomoc_OdlegloscKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBPomoc_OdlegloscKeyReleased(evt);
            }
        });

        jLPomoc1_Odleglosc.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc1_Odleglosc.setForeground(java.awt.Color.white);
        jLPomoc1_Odleglosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPomoc1_Odleglosc.setMaximumSize(new java.awt.Dimension(357, 16));
        jLPomoc1_Odleglosc.setPreferredSize(new java.awt.Dimension(357, 16));

        jLPomoc2_Odleglosc.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc2_Odleglosc.setForeground(java.awt.Color.white);
        jLPomoc2_Odleglosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPomoc2_Odleglosc.setMaximumSize(new java.awt.Dimension(357, 16));
        jLPomoc2_Odleglosc.setPreferredSize(new java.awt.Dimension(357, 16));

        jLPomoc3_Odleglosc.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc3_Odleglosc.setForeground(java.awt.Color.white);
        jLPomoc3_Odleglosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPomoc3_Odleglosc.setMaximumSize(new java.awt.Dimension(357, 16));
        jLPomoc3_Odleglosc.setPreferredSize(new java.awt.Dimension(357, 16));

        jLPomoc4_Odleglosc.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLPomoc4_Odleglosc.setForeground(java.awt.Color.white);
        jLPomoc4_Odleglosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLZapisano2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLZapisano2.setForeground(java.awt.Color.green);
        jLZapisano2.setMaximumSize(new java.awt.Dimension(60, 17));
        jLZapisano2.setMinimumSize(new java.awt.Dimension(60, 17));
        jLZapisano2.setPreferredSize(new java.awt.Dimension(60, 17));

        javax.swing.GroupLayout jPStrona2Layout = new javax.swing.GroupLayout(jPStrona2);
        jPStrona2.setLayout(jPStrona2Layout);
        jPStrona2Layout.setHorizontalGroup(
            jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStrona2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPStrona2Layout.createSequentialGroup()
                        .addComponent(jBReset_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBPrzelicz_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFMetry_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFCentymetry_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jLZapisano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPStrona2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTytulOdleglosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPStrona2Layout.createSequentialGroup()
                        .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBPomoc_Odleglosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLPomoc4_Odleglosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLPomoc2_Odleglosc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLPomoc3_Odleglosc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLPomoc1_Odleglosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPStrona2Layout.setVerticalGroup(
            jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStrona2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTytulOdleglosc)
                .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPStrona2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jTFCentymetry_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFMetry_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPStrona2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPStrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBPrzelicz_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBReset_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLPomoc3_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLPomoc2_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLPomoc1_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStrona2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLZapisano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))))
                    .addGroup(jPStrona2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLPomoc4_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPomoc_Odleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTBTresc.addTab("Odległość", jPStrona2);

        javax.swing.GroupLayout jPTrescLayout = new javax.swing.GroupLayout(jPTresc);
        jPTresc.setLayout(jPTrescLayout);
        jPTrescLayout.setHorizontalGroup(
            jPTrescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTBTresc)
        );
        jPTrescLayout.setVerticalGroup(
            jPTrescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTrescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTBTresc)
                .addContainerGap())
        );

        jMBMenu.setBackground(java.awt.Color.darkGray);
        jMBMenu.setBorder(null);
        jMBMenu.setForeground(java.awt.Color.white);

        jMPlik.setBackground(java.awt.Color.darkGray);
        jMPlik.setForeground(java.awt.Color.pink);
        jMPlik.setText("Plik");
        jMPlik.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMPlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPlikActionPerformed(evt);
            }
        });

        jMIPokazHistorie.setBackground(java.awt.Color.darkGray);
        jMIPokazHistorie.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMIPokazHistorie.setForeground(java.awt.Color.pink);
        jMIPokazHistorie.setText("Pokaż historię");
        jMIPokazHistorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPokazHistorieActionPerformed(evt);
            }
        });
        jMPlik.add(jMIPokazHistorie);

        jMIZamknij.setBackground(java.awt.Color.darkGray);
        jMIZamknij.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMIZamknij.setForeground(java.awt.Color.red);
        jMIZamknij.setText("Zamknij");
        jMIZamknij.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMIZamknijMouseClicked(evt);
            }
        });
        jMIZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIZamknijActionPerformed(evt);
            }
        });
        jMPlik.add(jMIZamknij);

        jMBMenu.add(jMPlik);

        jMOProgramie.setBackground(java.awt.Color.darkGray);
        jMOProgramie.setForeground(java.awt.Color.pink);
        jMOProgramie.setText("O programie");
        jMOProgramie.setFocusable(false);
        jMOProgramie.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMOProgramie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMOProgramieMouseClicked(evt);
            }
        });
        jMOProgramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOProgramieActionPerformed(evt);
            }
        });
        jMBMenu.add(jMOProgramie);

        setJMenuBar(jMBMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTresc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTresc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMIZamknijMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMIZamknijMouseClicked
        
    }//GEN-LAST:event_jMIZamknijMouseClicked

    private void jMIZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMIZamknijActionPerformed

    private void jMIPokazHistorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPokazHistorieActionPerformed
        jOPHistoria.showMessageDialog(null, "Odleglosci:       " + "Temperatura: ");
    }//GEN-LAST:event_jMIPokazHistorieActionPerformed

    private void jBPrzelicz_TemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrzelicz_TemperaturaActionPerformed
        String celcjusze = jTFCelcjusze_Temperatura.getText();
        String kelwiny = jTFKelwiny_Temperatura.getText();
        
        if ("Celcjusze".equals(celcjusze)) {
            kelwiny = jTFKelwiny_Temperatura.getText();
            int kelwiny_value = Integer.parseInt(kelwiny);

            int celcjusze_value = Math.abs(kelwiny_value) - 273;
            jTFCelcjusze_Temperatura.setText(""+celcjusze_value);
            } else if ("Kelwiny".equals(kelwiny)) {
            celcjusze = jTFCelcjusze_Temperatura.getText();
            int celcjusze_value = Integer.parseInt(celcjusze);
            
            int kelwiny_value = Math.abs(celcjusze_value) + 273;
            jTFKelwiny_Temperatura.setText(""+kelwiny_value);
        }
        
        try {
            FileWriter writer = new FileWriter("temperatura.txt", true);
            writer.write(celcjusze);
            writer.write(kelwiny);
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Przelicznik_jednostek.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLZapisano1.setText("Zapisano.");
    }//GEN-LAST:event_jBPrzelicz_TemperaturaActionPerformed

    private void jBReset_TemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReset_TemperaturaActionPerformed
        jTFKelwiny_Temperatura.setText("Kelwiny");
        jTFCelcjusze_Temperatura.setText("Celcjusze");
    }//GEN-LAST:event_jBReset_TemperaturaActionPerformed

    private void jBPomoc_TemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPomoc_TemperaturaActionPerformed
        jLPomoc1_Temperatura.setText("Wpisz w odpowiednie pole jednostke, którą chcesz przeliczyć");
        jLPomoc2_Temperatura.setText("zostawiając drugie pole. Jeżeli chcesz odwrócić proces");
        jLPomoc3_Temperatura.setText("kliknij przycisk resetuj i powtórz instrukcje");
        jLPomoc4_Temperatura.setText("ESC, aby ukryć");
    }//GEN-LAST:event_jBPomoc_TemperaturaActionPerformed

    private void jBPomoc_TemperaturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPomoc_TemperaturaKeyPressed
        if (evt.getKeyCode() == 27) {
            jLPomoc1_Temperatura.setText("");
            jLPomoc2_Temperatura.setText("");
            jLPomoc3_Temperatura.setText("");
            jLPomoc4_Temperatura.setText("");
        }
    }//GEN-LAST:event_jBPomoc_TemperaturaKeyPressed

    private void jBReset_OdlegloscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReset_OdlegloscActionPerformed
        jTFCentymetry_Odleglosc.setText("Centymetry");
        jTFMetry_Odleglosc.setText("Metry");
    }//GEN-LAST:event_jBReset_OdlegloscActionPerformed

    private void jBPrzelicz_OdlegloscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrzelicz_OdlegloscActionPerformed
        String centymetry = jTFCentymetry_Odleglosc.getText();
        String metry = jTFMetry_Odleglosc.getText();
        
        if ("Centymetry".equals(centymetry)) {
            metry = jTFMetry_Odleglosc.getText();
            double metry_value = Double.parseDouble(metry);
            
            double centymetry_value = Math.abs(metry_value) * 100;
            jTFCentymetry_Odleglosc.setText(""+centymetry_value);
        } else if ("Metry".equals(metry)) {
            centymetry = jTFCentymetry_Odleglosc.getText();
            double centymetry_value = Double.parseDouble(centymetry);
            
            double metry_value = Math.abs(centymetry_value) / 100;
            jTFMetry_Odleglosc.setText(""+metry_value);
        }
        
        try {
            FileWriter writer = new FileWriter("odleglosc.txt", true);
            writer.write(centymetry);
            writer.write(metry);
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Przelicznik_jednostek.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLZapisano2.setText("Zapisano.");
    }//GEN-LAST:event_jBPrzelicz_OdlegloscActionPerformed

    private void jBPomoc_OdlegloscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPomoc_OdlegloscActionPerformed
        jLPomoc1_Odleglosc.setText("Wpisz w odpowiednie pole jednostke, którą chcesz przeliczyć");
        jLPomoc2_Odleglosc.setText("zostawiając drugie pole. Jeżeli chcesz odwrócić proces");
        jLPomoc3_Odleglosc.setText("kliknij przycisk resetuj i powtórz instrukcje");
        jLPomoc4_Odleglosc.setText("ESC, aby ukryć");
    }//GEN-LAST:event_jBPomoc_OdlegloscActionPerformed

    private void jBPomoc_OdlegloscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPomoc_OdlegloscKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPomoc_OdlegloscKeyPressed

    private void jBPomoc_OdlegloscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPomoc_OdlegloscKeyReleased
        if (evt.getKeyCode() == 27) {
            jLPomoc1_Odleglosc.setText("");
            jLPomoc2_Odleglosc.setText("");
            jLPomoc3_Odleglosc.setText("");
            jLPomoc4_Odleglosc.setText("");
        }
    }//GEN-LAST:event_jBPomoc_OdlegloscKeyReleased

    private void jOPHistoriaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jOPHistoriaAncestorAdded

    }//GEN-LAST:event_jOPHistoriaAncestorAdded

    private void jMPlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPlikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMPlikActionPerformed

    private void jMOProgramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOProgramieActionPerformed
        
    }//GEN-LAST:event_jMOProgramieActionPerformed

    private void jMOProgramieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMOProgramieMouseClicked
        jOPOprogramie.showMessageDialog(null, "Autor: Antoni Musiał");
    }//GEN-LAST:event_jMOProgramieMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przelicznik_jednostek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPomoc_Odleglosc;
    private javax.swing.JButton jBPomoc_Temperatura;
    private javax.swing.JButton jBPrzelicz_Odleglosc;
    private javax.swing.JButton jBPrzelicz_Temperatura;
    private javax.swing.JButton jBReset_Odleglosc;
    private javax.swing.JButton jBReset_Temperatura;
    private javax.swing.JDialog jDHistoria;
    private javax.swing.JDialog jDOprogramie;
    private javax.swing.JDialog jDPomoc;
    private javax.swing.JLabel jLPomoc1_Odleglosc;
    private javax.swing.JLabel jLPomoc1_Temperatura;
    private javax.swing.JLabel jLPomoc2_Odleglosc;
    private javax.swing.JLabel jLPomoc2_Temperatura;
    private javax.swing.JLabel jLPomoc3_Odleglosc;
    private javax.swing.JLabel jLPomoc3_Temperatura;
    private javax.swing.JLabel jLPomoc4_Odleglosc;
    private javax.swing.JLabel jLPomoc4_Temperatura;
    private javax.swing.JLabel jLTytulOdleglosc;
    private javax.swing.JLabel jLTytulTemperatura;
    private javax.swing.JLabel jLZapisano1;
    private javax.swing.JLabel jLZapisano2;
    private javax.swing.JMenuBar jMBMenu;
    private javax.swing.JMenuItem jMIPokazHistorie;
    private javax.swing.JMenuItem jMIZamknij;
    private javax.swing.JMenu jMOProgramie;
    private javax.swing.JMenu jMPlik;
    private javax.swing.JOptionPane jOPHistoria;
    private javax.swing.JOptionPane jOPOprogramie;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPStrona1;
    private javax.swing.JPanel jPStrona2;
    private javax.swing.JPanel jPTresc;
    private javax.swing.JTabbedPane jTBTresc;
    private javax.swing.JTextField jTFCelcjusze_Temperatura;
    private javax.swing.JTextField jTFCentymetry_Odleglosc;
    private javax.swing.JTextField jTFKelwiny_Temperatura;
    private javax.swing.JTextField jTFMetry_Odleglosc;
    // End of variables declaration//GEN-END:variables
}
