
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JSlider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author musialantoni
 */
public class RGB_color_changer extends javax.swing.JFrame {

    /**
     * Creates new form RGB_color_changer
     */
    int r, g, b;
    
    String hex = String.format("#%02x%02x%02x", r, g, b);
    
    public RGB_color_changer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Everything = new javax.swing.JPanel();
        jP_RED_Slider = new javax.swing.JPanel();
        jL_RED_Slider = new javax.swing.JLabel();
        jS_RED_Slider = new javax.swing.JSlider();
        jP_GREEN_Slider = new javax.swing.JPanel();
        jL_GREEN_Slider = new javax.swing.JLabel();
        jS_GREEN_Slider = new javax.swing.JSlider();
        jP_BLUE_Slider = new javax.swing.JPanel();
        jL_BLUE_Slider = new javax.swing.JLabel();
        jS_BLUE_Slider = new javax.swing.JSlider();
        jP_Properties_from_sliders = new javax.swing.JPanel();
        jP_RED_Properties_from_slider = new javax.swing.JPanel();
        jL_RED_Properties_from_slider = new javax.swing.JLabel();
        jL_RED_Properties_from_slider_value = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jP_GREEN_Properties_from_slider = new javax.swing.JPanel();
        jL_GREEN_Properties_from_slider = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jL_GREEN_Properties_from_slider_value = new javax.swing.JLabel();
        jP_BLUE_Properties_from_slider = new javax.swing.JPanel();
        jL_BLUE_Properties_from_slider = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jL_BLUE_Properties_from_slider_value = new javax.swing.JLabel();
        jP_Color_Changing = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTF_Hex = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jP_Everything.setBackground(java.awt.Color.darkGray);

        jP_RED_Slider.setBackground(java.awt.Color.gray);

        jL_RED_Slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_RED_Slider.setForeground(java.awt.Color.white);
        jL_RED_Slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_RED_Slider.setText("Red");

        jS_RED_Slider.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jS_RED_Slider.setForeground(java.awt.Color.white);
        jS_RED_Slider.setMajorTickSpacing(25);
        jS_RED_Slider.setMaximum(255);
        jS_RED_Slider.setMinorTickSpacing(1);
        jS_RED_Slider.setPaintLabels(true);
        jS_RED_Slider.setSnapToTicks(true);
        jS_RED_Slider.setValue(100);
        jS_RED_Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_RED_SliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jP_RED_SliderLayout = new javax.swing.GroupLayout(jP_RED_Slider);
        jP_RED_Slider.setLayout(jP_RED_SliderLayout);
        jP_RED_SliderLayout.setHorizontalGroup(
            jP_RED_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_RED_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_RED_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_RED_SliderLayout.setVerticalGroup(
            jP_RED_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_RED_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_RED_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS_RED_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_GREEN_Slider.setBackground(java.awt.Color.gray);

        jL_GREEN_Slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_GREEN_Slider.setForeground(java.awt.Color.white);
        jL_GREEN_Slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_GREEN_Slider.setText("Green");

        jS_GREEN_Slider.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jS_GREEN_Slider.setForeground(java.awt.Color.white);
        jS_GREEN_Slider.setMajorTickSpacing(25);
        jS_GREEN_Slider.setMaximum(255);
        jS_GREEN_Slider.setMinorTickSpacing(1);
        jS_GREEN_Slider.setPaintLabels(true);
        jS_GREEN_Slider.setSnapToTicks(true);
        jS_GREEN_Slider.setValue(100);
        jS_GREEN_Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_GREEN_SliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jP_GREEN_SliderLayout = new javax.swing.GroupLayout(jP_GREEN_Slider);
        jP_GREEN_Slider.setLayout(jP_GREEN_SliderLayout);
        jP_GREEN_SliderLayout.setHorizontalGroup(
            jP_GREEN_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_GREEN_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_GREEN_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_GREEN_SliderLayout.setVerticalGroup(
            jP_GREEN_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_GREEN_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_GREEN_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS_GREEN_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_BLUE_Slider.setBackground(java.awt.Color.gray);

        jL_BLUE_Slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_BLUE_Slider.setForeground(java.awt.Color.white);
        jL_BLUE_Slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_BLUE_Slider.setText("Blue");

        jS_BLUE_Slider.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jS_BLUE_Slider.setForeground(java.awt.Color.white);
        jS_BLUE_Slider.setMajorTickSpacing(25);
        jS_BLUE_Slider.setMaximum(255);
        jS_BLUE_Slider.setMinorTickSpacing(1);
        jS_BLUE_Slider.setPaintLabels(true);
        jS_BLUE_Slider.setSnapToTicks(true);
        jS_BLUE_Slider.setValue(100);
        jS_BLUE_Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_BLUE_SliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jP_BLUE_SliderLayout = new javax.swing.GroupLayout(jP_BLUE_Slider);
        jP_BLUE_Slider.setLayout(jP_BLUE_SliderLayout);
        jP_BLUE_SliderLayout.setHorizontalGroup(
            jP_BLUE_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_BLUE_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_BLUE_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_BLUE_SliderLayout.setVerticalGroup(
            jP_BLUE_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BLUE_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_BLUE_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS_BLUE_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_Properties_from_sliders.setBackground(java.awt.Color.gray);

        jP_RED_Properties_from_slider.setBackground(java.awt.Color.lightGray);

        jL_RED_Properties_from_slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_RED_Properties_from_slider.setForeground(java.awt.Color.red);
        jL_RED_Properties_from_slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_RED_Properties_from_slider.setText("RED");

        jL_RED_Properties_from_slider_value.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_RED_Properties_from_slider_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_RED_Properties_from_slider_value.setText("100");

        jSeparator1.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jP_RED_Properties_from_sliderLayout = new javax.swing.GroupLayout(jP_RED_Properties_from_slider);
        jP_RED_Properties_from_slider.setLayout(jP_RED_Properties_from_sliderLayout);
        jP_RED_Properties_from_sliderLayout.setHorizontalGroup(
            jP_RED_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_RED_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jL_RED_Properties_from_slider, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jL_RED_Properties_from_slider_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_RED_Properties_from_sliderLayout.setVerticalGroup(
            jP_RED_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_RED_Properties_from_slider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_RED_Properties_from_slider_value)
                .addContainerGap())
        );

        jP_GREEN_Properties_from_slider.setBackground(java.awt.Color.lightGray);

        jL_GREEN_Properties_from_slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_GREEN_Properties_from_slider.setForeground(java.awt.Color.green);
        jL_GREEN_Properties_from_slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_GREEN_Properties_from_slider.setText("Green");

        jSeparator2.setForeground(java.awt.Color.black);

        jL_GREEN_Properties_from_slider_value.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_GREEN_Properties_from_slider_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_GREEN_Properties_from_slider_value.setText("100");

        javax.swing.GroupLayout jP_GREEN_Properties_from_sliderLayout = new javax.swing.GroupLayout(jP_GREEN_Properties_from_slider);
        jP_GREEN_Properties_from_slider.setLayout(jP_GREEN_Properties_from_sliderLayout);
        jP_GREEN_Properties_from_sliderLayout.setHorizontalGroup(
            jP_GREEN_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_GREEN_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_GREEN_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_GREEN_Properties_from_slider_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_GREEN_Properties_from_sliderLayout.setVerticalGroup(
            jP_GREEN_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_GREEN_Properties_from_slider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_GREEN_Properties_from_slider_value)
                .addContainerGap())
        );

        jP_BLUE_Properties_from_slider.setBackground(java.awt.Color.lightGray);

        jL_BLUE_Properties_from_slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_BLUE_Properties_from_slider.setForeground(java.awt.Color.blue);
        jL_BLUE_Properties_from_slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_BLUE_Properties_from_slider.setText("BLUE");

        jSeparator3.setForeground(java.awt.Color.black);

        jL_BLUE_Properties_from_slider_value.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_BLUE_Properties_from_slider_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_BLUE_Properties_from_slider_value.setText("100");

        javax.swing.GroupLayout jP_BLUE_Properties_from_sliderLayout = new javax.swing.GroupLayout(jP_BLUE_Properties_from_slider);
        jP_BLUE_Properties_from_slider.setLayout(jP_BLUE_Properties_from_sliderLayout);
        jP_BLUE_Properties_from_sliderLayout.setHorizontalGroup(
            jP_BLUE_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BLUE_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3)
                    .addComponent(jL_BLUE_Properties_from_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_BLUE_Properties_from_slider_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_BLUE_Properties_from_sliderLayout.setVerticalGroup(
            jP_BLUE_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_BLUE_Properties_from_slider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_BLUE_Properties_from_slider_value)
                .addContainerGap())
        );

        jP_Color_Changing.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jP_Color_ChangingLayout = new javax.swing.GroupLayout(jP_Color_Changing);
        jP_Color_Changing.setLayout(jP_Color_ChangingLayout);
        jP_Color_ChangingLayout.setHorizontalGroup(
            jP_Color_ChangingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jP_Color_ChangingLayout.setVerticalGroup(
            jP_Color_ChangingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HTML");

        jSeparator4.setForeground(java.awt.Color.black);

        jTF_Hex.setBackground(java.awt.Color.lightGray);
        jTF_Hex.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTF_Hex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_Hex.setText("#ffffff");
        jTF_Hex.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jTF_Hex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_HexKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTF_Hex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jTF_Hex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_Properties_from_slidersLayout = new javax.swing.GroupLayout(jP_Properties_from_sliders);
        jP_Properties_from_sliders.setLayout(jP_Properties_from_slidersLayout);
        jP_Properties_from_slidersLayout.setHorizontalGroup(
            jP_Properties_from_slidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Properties_from_slidersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_RED_Properties_from_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_GREEN_Properties_from_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_BLUE_Properties_from_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jP_Color_Changing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_Properties_from_slidersLayout.setVerticalGroup(
            jP_Properties_from_slidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Properties_from_slidersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_Properties_from_slidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_Color_Changing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_BLUE_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_GREEN_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_RED_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_Properties_from_slidersLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Koralowy");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.darkGray);
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Łososiowy");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.darkGray);
        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Cyan");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.darkGray);
        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setForeground(java.awt.Color.white);
        jButton4.setText("Beżowy");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.darkGray);
        jButton5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton5.setForeground(java.awt.Color.white);
        jButton5.setText("Miedziany");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(java.awt.Color.darkGray);
        jButton6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton6.setForeground(java.awt.Color.white);
        jButton6.setText("Gumiguta");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jP_EverythingLayout = new javax.swing.GroupLayout(jP_Everything);
        jP_Everything.setLayout(jP_EverythingLayout);
        jP_EverythingLayout.setHorizontalGroup(
            jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EverythingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_BLUE_Slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_GREEN_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_RED_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP_EverythingLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jP_EverythingLayout.createSequentialGroup()
                                .addComponent(jP_Properties_from_sliders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(jP_EverythingLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jP_EverythingLayout.setVerticalGroup(
            jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EverythingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_RED_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_GREEN_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_BLUE_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jP_Properties_from_sliders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Everything, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Everything, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jS_RED_SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_RED_SliderStateChanged
        // TODO add your handling code here:
        r = jS_RED_Slider.getValue();
        jP_Color_Changing.setBackground(new Color(r, g, b));
        jL_RED_Properties_from_slider_value.setText("" + r);
        String hex = String.format("#%02x%02x%02x", r, g, b);
        jTF_Hex.setText("" + hex);
    }//GEN-LAST:event_jS_RED_SliderStateChanged

    private void jS_GREEN_SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_GREEN_SliderStateChanged
        // TODO add your handling code here:
        g = jS_GREEN_Slider.getValue();
        jP_Color_Changing.setBackground(new Color(r, g, b));
        jL_GREEN_Properties_from_slider_value.setText("" + g);
        String hex = String.format("#%02x%02x%02x", r, g, b);
        jTF_Hex.setText("" + hex);
    }//GEN-LAST:event_jS_GREEN_SliderStateChanged

    private void jS_BLUE_SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_BLUE_SliderStateChanged
        // TODO add your handling code here:
        b = jS_BLUE_Slider.getValue();
        jP_Color_Changing.setBackground(new Color(r, g, b));
        jL_BLUE_Properties_from_slider_value.setText("" + b);
        String hex = String.format("#%02x%02x%02x", r, g, b);
        jTF_Hex.setText("" + hex);
    }//GEN-LAST:event_jS_BLUE_SliderStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jP_Color_Changing.setBackground(new Color(255, 127, 80));
        jL_RED_Properties_from_slider_value.setText("255");
        jL_GREEN_Properties_from_slider_value.setText("127");
        jL_BLUE_Properties_from_slider_value.setText("80");
        jTF_Hex.setText("#FA8072");
        jS_RED_Slider.setValue(255);
        jS_GREEN_Slider.setValue(127);
        jS_BLUE_Slider.setValue(80);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jP_Color_Changing.setBackground(new Color(255, 128, 114));
        jL_RED_Properties_from_slider_value.setText("255");
        jL_GREEN_Properties_from_slider_value.setText("128");
        jL_BLUE_Properties_from_slider_value.setText("114");
        jTF_Hex.setText("#FF7F50");
        jS_RED_Slider.setValue(255);
        jS_GREEN_Slider.setValue(128);
        jS_BLUE_Slider.setValue(114);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jP_Color_Changing.setBackground(new Color(224, 255, 255));
        jL_RED_Properties_from_slider_value.setText("224");
        jL_GREEN_Properties_from_slider_value.setText("255");
        jL_BLUE_Properties_from_slider_value.setText("255");
        jTF_Hex.setText("#E0FFFF");
        jS_RED_Slider.setValue(224);
        jS_GREEN_Slider.setValue(255);
        jS_BLUE_Slider.setValue(255);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        jP_Color_Changing.setBackground(new Color(217, 186, 140));
        jL_RED_Properties_from_slider_value.setText("217");
        jL_GREEN_Properties_from_slider_value.setText("186");
        jL_BLUE_Properties_from_slider_value.setText("140");
        jTF_Hex.setText("#D9BA8C");
        jS_RED_Slider.setValue(217);
        jS_GREEN_Slider.setValue(186);
        jS_BLUE_Slider.setValue(140);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jP_Color_Changing.setBackground(new Color(133, 56, 43));
        jL_RED_Properties_from_slider_value.setText("133");
        jL_GREEN_Properties_from_slider_value.setText("56");
        jL_BLUE_Properties_from_slider_value.setText("43");
        jTF_Hex.setText("#85382B");
        jS_RED_Slider.setValue(133);
        jS_GREEN_Slider.setValue(56);
        jS_BLUE_Slider.setValue(43);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        jP_Color_Changing.setBackground(new Color(228, 155, 15));
        jL_RED_Properties_from_slider_value.setText("228");
        jL_GREEN_Properties_from_slider_value.setText("155");
        jL_BLUE_Properties_from_slider_value.setText("15");
        jTF_Hex.setText("#E49B0F");
        jS_RED_Slider.setValue(228);
        jS_GREEN_Slider.setValue(155);
        jS_BLUE_Slider.setValue(15);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTF_HexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_HexKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String Hex_text = jTF_Hex.getText();
            jP_Color_Changing.setBackground(Color.decode(Hex_text));
        }
    }//GEN-LAST:event_jTF_HexKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RGB_color_changer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jL_BLUE_Properties_from_slider;
    private javax.swing.JLabel jL_BLUE_Properties_from_slider_value;
    private javax.swing.JLabel jL_BLUE_Slider;
    private javax.swing.JLabel jL_GREEN_Properties_from_slider;
    private javax.swing.JLabel jL_GREEN_Properties_from_slider_value;
    private javax.swing.JLabel jL_GREEN_Slider;
    private javax.swing.JLabel jL_RED_Properties_from_slider;
    private javax.swing.JLabel jL_RED_Properties_from_slider_value;
    private javax.swing.JLabel jL_RED_Slider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jP_BLUE_Properties_from_slider;
    private javax.swing.JPanel jP_BLUE_Slider;
    private javax.swing.JPanel jP_Color_Changing;
    private javax.swing.JPanel jP_Everything;
    private javax.swing.JPanel jP_GREEN_Properties_from_slider;
    private javax.swing.JPanel jP_GREEN_Slider;
    private javax.swing.JPanel jP_Properties_from_sliders;
    private javax.swing.JPanel jP_RED_Properties_from_slider;
    private javax.swing.JPanel jP_RED_Slider;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jS_BLUE_Slider;
    private javax.swing.JSlider jS_GREEN_Slider;
    private javax.swing.JSlider jS_RED_Slider;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTF_Hex;
    // End of variables declaration//GEN-END:variables
}
